# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3f06e418456f8b9861ff642cbb59732a5d936951adb2d69ce560706053b87bad8a30c099fc5a6b3efed980da0d94a8dc1ee617fc0085bfaf6d33ec37e49f75e

test:
  secret_key_base: e62b33d28d22f2f64cb70ba0f2c5b62db0932ba99f2c949e9816900b704c43f8baf866c6038e1ff340a56664cfdb395845704071225791425f412caa9a198dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
